nameOverride: ''
image:
  registry: docker.io
  pullPolicy: IfNotPresent
  app:
    registry: null
    imageLocation: null
    tag: ''
    pullPolicy: null
  liquibase:
    registry: null
    imageLocation: null
    tag: 1.2.0
    pullPolicy: null
imagePullSecrets: []
env:
  type: ''
  label: ''
datasource:
  host: ''
  port: ''
  dbName: ''
  user: ''
  globalSchemaPrefix: wo
  connTimeout: 60000
  maxPoolSize: 2
  minIdle: 0
  idleTimeout: 120000
  connectionParams: {}
liquibase:
  enabled: true
  syncOnly: false
  user: ''
  role: ''
  replicationRole: ''
  resources: {}
members:
- businessUnit: ''
  applicationMember: ''
  memberSign: ''
  liquibase:
    role: ''
    replicationRole: ''
  datasource:
    globalSchema: false
    host: ''
    port: ''
    dbName: ''
    user: ''
    password: ''
    connTimeout: ''
    maxPoolSize: ''
    minIdle: 0
kafka:
  readinessProbeEnabled: true
  user: ''
  servers: ''
  saslMechanism: PLAIN
  securityProtocol: SASL_SSL
  autoOffsetReset: earliest
  maxPollInterval: 300000
  trxTimeout: 60000
  sslEndpointIdentAlg: HTTPS
  schemaRegistry:
    credSource: USER_INFO
    user: ''
    url: ''
  topics:
    confirmpersoncreation:
      name: hr.vestigo.hp.confirmpersoncreation
      consumerGroup: hr.vestigo.hp.confirmpersoncreation
    personregistrylinks:
      name: hr.vestigo.hp.personregistrylinks
    superperson:
      name: hr.vestigo.hp.superperson
      consumerGroup: hr.vestigo.hp.superperson
    superpersoncreation:
      name: hr.vestigo.hp.superpersoncreation
oauth2:
  enabled: false
  resourceUri: ''
  resource: sup
  authorizationPrefix: ''
request:
  sanitization:
    enabled: true
response:
  encoding:
    enabled: false
kafkaService:
  technicalUserId: PIFNTFMS
  deliveryChannel: BOS
  cmsAppModule: DCC
  preintAppModule: PREINT
personRegistry:
  getSpLinks:
    baseUrl: ''
    timeout: ''
timezone: ''
secret:
  decryptionKey: ''
  datasourcePassword: ''
  kafkaPassword: ''
  kafkaSchemaRegistryPassword: ''
  liquibasePassword: ''
  trustStorePassword: ''
  keyStorePassword: ''
  cmsRestPassword: ''
  oauth2ClientToken: ''
logger:
  format: STRING
  level:
    health: INFO
    kafka: INFO
    kafkaCore: INFO
    rest: INFO
    database: INFO
    databaseSql: DEBUG
    databaseBind: TRACE
    databaseExtract: TRACE
    databaseSlowQuery: INFO
    businessLogic: INFO
    general: INFO
  logToFile: false
  rollingFileAppender: false
  logDir: /var/log/app
  logDirMount:
    enabled: false
  microserviceTag: PREINT
  databaseSlowQueryThreshold: 0
healthStatusDownReturnCode: '418'
javaOpts: -Xms256M -Xmx256M
podAnnotations: {}
podLabels: {}
deploymentAnnotations: {}
serviceAnnotations: {}
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
securityContext: {}
service:
  enabled: true
  type: ClusterIP
  port: 8443
  nodePort: ''
  clusterIP: ''
  loadBalancerIP: ''
  loadBalancerSourceRanges: []
  annotations: {}
  labels: {}
ingress:
  enabled: false
  className: ''
  annotations: {}
  hosts: []
  tls: []
  labels: {}
resources:
  limits:
    cpu: 500m
    memory: 768Mi
  requests:
    cpu: 50m
    memory: 768Mi
initContainers: []
nodeSelector: {}
tolerations: []
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/arch
          operator: In
          values:
          - amd64
        - key: kubernetes.io/os
          operator: In
          values:
          - linux
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - person-registry-interface
        topologyKey: kubernetes.io/hostname
deployment:
  replicaCount: 1
  annotations: {}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 60
  terminationGracePeriodSeconds: 60
  restartPolicy: Always
  readinessProbe:
    initialDelaySeconds: 0
    periodSeconds: 60
    timeoutSeconds: 10
    successThreshold: 1
    failureThreshold: 2
    httpGet:
      path: /health/readiness
      port: http
      scheme: HTTPS
  livenessProbe:
    initialDelaySeconds: 0
    periodSeconds: 60
    timeoutSeconds: 10
    failureThreshold: 3
    httpGet:
      path: /health/liveness
      port: http
      scheme: HTTPS
  startupProbe:
    initialDelaySeconds: 30
    periodSeconds: 5
    timeoutSeconds: 1
    failureThreshold: 60
    httpGet:
      path: /health/liveness
      port: http
      scheme: HTTPS
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
vpa:
  enabled: false
  updateMode: 'Off'
mountServerCertFromSecret:
  enabled: false
  secretName: ''
  certPath: ''
  keyPath: ''
mountKeyStoreFromSecret:
  enabled: false
  secretName: ''
  keyStoreName: ''
  keyStoreType: JKS
mountTrustStoreFromSecret:
  enabled: false
  secretName: ''
  trustStoreName: ''
  trustStoreType: JKS
mountCaFromSecret:
  enabled: false
  secretName: ''
customVolumes: []
customMounts: []
customEnv: []
