apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "person-registry-web.name" . }}
  labels:
    {{- include "person-registry-web.labels" . | nindent 4 }}
{{- with .Values.deployment.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.deployment.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.deployment.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "person-registry-web.selectorLabels" . | nindent 6 }}
  strategy:
    {{- toYaml .Values.deployment.strategy | nindent 4 }}
  minReadySeconds: {{ .Values.deployment.minReadySeconds }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "person-registry-web.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      terminationGracePeriodSeconds: {{ .Values.deployment.terminationGracePeriodSeconds }}
      restartPolicy: {{ .Values.deployment.restartPolicy }}
      {{- if .Values.initContainers }}
      initContainers:
        {{- with .Values.initContainers }}
        {{- toYaml . | trim | nindent 8 }}
        {{- end }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "person-registry-web.app.repository" . }}:{{ .Values.image.app.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ include "person-registry-web.app.imagePullPolicy" . }}
          env:
            {{- if .Values.timezone }}
            - name: TZ
              value: {{ .Values.timezone }}
            {{- end }}
            - name: REACT_APP_API_GATEWAY_URL
              value: {{ required "Please specify API Gateway URL apiGatewayUrl" .Values.apiGatewayUrl | quote }}
            - name: REACT_APP_API_URL
              value: "{{ .Values.apiGatewayUrl }}"
            - name: REACT_APP_ENVIRONMENT
              value: {{ required "Please specify environment name in environmentName" .Values.environmentName | quote }}
            - name: REACT_APP_SESSION_TIMEOUT_IN_SECONDS
              value: {{ required "Please specify HTTP session timeout in httpSessionTimeout" .Values.httpSessionTimeout | quote }}
            - name: REACT_APP_SESSION_TIMEOUT_MESSAGE
              value: "Session expired! Please login."
            - name: REACT_OAUTH_AUTH_ENABLED
              value: {{ .Values.oauth2.enabled | quote }}
            {{- if .Values.oauth2.enabled }}
            - name: REACT_OAUTH_AUTH_SERVER_URL
              value: >-
                {{ required "Please specify Keycloak server URL in oauth2.serverUrl" .Values.oauth2.serverUrl }}/realms/{{ required "Please specify Keycloak realm name in oauth2.realm" .Values.oauth2.realm }}
            - name: REACT_OAUTH_CLIENT_ID
              value: {{ required "Please specify Keycloak resource name in oauth2.resource" .Values.oauth2.resource | quote }}
            {{- else }}
            - name: REACT_OAUTH_AUTH_SERVER_URL
              value: N/A
            - name: REACT_OAUTH_CLIENT_ID
              value: N/A
            {{- end }}
            - name: REACT_MULTIMEMBER_ENABLED
              value: {{ .Values.multimemberEnabled | quote }}
            {{- with .Values.customEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: 8443
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.deployment.livenessProbe | nindent 12 }}
          {{- if and .Values.deployment.readinessProbe.enabled .Values.internalBackendServiceUrl }}
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - curl -f -s -k -m 5 {{ .Values.internalBackendServiceUrl | quote }}/health/readiness
            initialDelaySeconds: {{ .Values.deployment.readinessProbe.initialDelaySeconds | default 10 }}
            periodSeconds: {{ .Values.deployment.readinessProbe.periodSeconds | default 10 }}
            timeoutSeconds: {{ .Values.deployment.readinessProbe.timeoutSeconds | default 10 }}
            successThreshold: {{ .Values.deployment.readinessProbe.successThreshold | default 1 }}
            failureThreshold: {{ .Values.deployment.readinessProbe.failureThreshold | default 3 }}
          {{- else if .Values.deployment.readinessProbe.enabled }}
          {{- fail "readinessProbe is enabled but internalBackendServiceUrl is not set" }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- include "person-registry-web.mounts" . | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- include "person-registry-web.volumes" . | nindent 8 }}
