apiVersion: v1
kind: Service
metadata:
  name: {{ include "transaction-streaming.name" . }}-headless
  labels:
    {{- include "transaction-streaming.labels" . | nindent 4 }}
    {{- if .Values.service.labels }}
    {{ toYaml .Values.service.labels | indent 4 }}
    {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
    prometheus.io/path: /prometheus
    prometheus.io/port: {{ .Values.service.port }}
    prometheus.io/scheme: https
    prometheus.io/scrape: 'true'
  {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      {{- if contains "NodePort" .Values.service.type }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      targetPort: http
      protocol: TCP
      name: http
  clusterIP: None
  selector:
    {{- include "transaction-streaming.selectorLabels" . | nindent 4 }}