apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  application.yaml: |-
    {{- include "api-gateway.appConfig" . | nindent 4 }}
    
  log4j2.xml: |-
    {{- include "api-gateway.logger" . | nindent 4 }}