 {{- if not .Values.secret.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
data:
  password.conf: |-
    {{- include "payment-order.passwords" . | nindent 4 }}
    {{- end }}
